name: "AI Code Reviewer"
description: "A GitHub Action to review code using OpenAI's GPT-4 API"
inputs:
  GITHUB_TOKEN:
    description: "GitHub token"
    required: true
  OPENAI_API_KEY:
    description: "OpenAI API key"
    required: true
  OPENAI_API_MODEL:
    description: "OpenAI API model"
    required: false
    default: "gpt-4"
  exclude:
    description: "Exclude patterns"
    required: false
runs:
  using: "composite"
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: Restore dependencies
      run: dotnet restore
      shell: bash
    - name: Build
      run: dotnet build --configuration Release
      shell: bash
    - name: Run AI Code Reviewer
      run: dotnet run --project path/to/your/project.csproj
      shell: bash
