name: AI Code Reviewer

on:
  pull_request:
    types:
      - opened
      - synchronize
permissions:
  contents: write
  pull-requests: write
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x' # Ensure this is the required version that supports .NET 8.0

      - name: Verify .NET SDK Version
        run: dotnet --version

      - name: Clear NuGet Cache
        run: dotnet nuget locals all --clear

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal
     
